# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Search for Secret Keys

on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  get-files:
    name: Secret Key Search
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: modified files
        run: |
          changedFiles=$(git diff --name-only --diff-filter=d)
          if grep -q "['|\"]?([a|A][p|P][i|I][_]?[k|K][e|E][y|Y]|[c|C][u|U][r|R]{2}[e|E][n|N][t|T][_]?[k|K][e|E][y|Y])['|\"]?.*(['|\"][0-9a-zA-Z_-]{32,45}['|\"])"; then
            echo "::error title={KeyFound}::Secret Key found"
            exit 1
          fi
          exit 0
