# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Search for Secret Keys

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  get-files:
    name: Secret Key Search
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: modified files
        run: |
          case '${{ github.event_name }}' in
            push)
              firstCommit='${{ github.event.commits[0].id }}'
              lastCommit='${{ github.event.commits[-1].id }}'
              ;;
            pull_request)
              firstCommit='${{ github.event.base_ref }}'
              lastCommit='${{ github.event.head_ref }}'
              ;;
          esac
          changedFiles=$(git diff --name-only --diff-filter=d "${firstCommit}~1" "${lastCommit}")
          foundKeys=$(grep -inE '(AKIA[0-9A-Z]{16}|[A-Za-z0-9]{32}|AIza[0-9A-Za-z_-]{35})')
          if [[ -z $foundKeys ]]; then
            echo -e "::error Key found here:\n$foundKeys"
            exit 1
          fi
