# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Search for Secret Keys

on:
  pull_request:
    branches:
      - main

jobs:
  get-files:
    name: Secret Key Search
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: modified files
        run: |
          echo "::notice title={testEcho}::Running script"
          changedFiles=$(git diff --name-only --diff-filter=d)
          if grep -qE '(AKIA[0-9A-Z]{16}|[A-Za-z0-9]{32}|AIza[0-9A-Za-z_-]{35})'; then
            echo "::notice title={KeyFound}::Key found"
            exit 0
          fi
          exit 0
